title:              Ian Dalrymple
email:              iandalrymple6@gmail.com
description:        Professional Portfolio
author:             Ian Dalrymple
baseurl:            ""
url:                "https://iandalrymple.github.io"

# Social Profiles
twitter_username:   
github_username:    iandalrymple
facebook_username:  
instagram_username:  
linkedin_username:  ian-dalrymple-21abbb13

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
